# Generated by Django 2.0.5 on 2018-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('heading', models.CharField(blank=True, max_length=120)),
                ('paragraph', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='about_img')),
                ('img_width', models.CharField(default=0, max_length=20)),
                ('img_height', models.CharField(default=0, max_length=20)),
            ],
            options={
                'db_table': 'aboutpagecontent',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(blank=True, upload_to='articles_img')),
                ('img_width', models.CharField(default=0, max_length=20)),
                ('img_height', models.CharField(default=0, max_length=20)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='homePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('heading', models.CharField(blank=True, max_length=120)),
                ('paragraph', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='home_img')),
                ('img_width', models.CharField(default=0, max_length=20)),
                ('img_height', models.CharField(default=0, max_length=20)),
            ],
            options={
                'db_table': 'homepagecontent',
                'ordering': ['id'],
            },
        ),
    ]
